pub fn tla_to_flag(tla: Option<&str>) -> Option<String> {
    if let Some(tla) = tla {
        match tla {
            "ALB" => Some("al".into()),
            "ALG" => Some("dz".into()),
            "ARG" => Some("ar".into()),
            "AUS" => Some("au".into()),
            "AUT" => Some("at".into()),
            "BEL" => Some("be".into()),
            "BIH" => Some("ba".into()),
            "BRA" => Some("br".into()),
            "CAN" => Some("ca".into()),
            "CIV" => Some("ci".into()),
            "COD" => Some("cd".into()),
            "COL" => Some("co".into()),
            "CPV" => Some("cv".into()),
            "CRO" => Some("hr".into()),
            "CUR" => Some("cw".into()),
            "CZE" => Some("cz".into()),
            "DEN" => Some("dk".into()),
            "ECU" => Some("ec".into()),
            "EGY" => Some("eg".into()),
            "ENG" => Some("gb-eng".into()),
            "ESP" => Some("es".into()),
            "FRA" => Some("fr".into()),
            "GEO" => Some("ge".into()),
            "GER" => Some("de".into()),
            "GHA" => Some("gh".into()),
            "HAI" => Some("ht".into()),
            "HUN" => Some("hu".into()),
            "IRN" => Some("ir".into()),
            "IRQ" => Some("iq".into()),
            "ITA" => Some("it".into()),
            "JOR" => Some("jo".into()),
            "JPN" => Some("jp".into()),
            "KOR" => Some("ko".into()),
            "KSA" => Some("sa".into()),
            "MAR" => Some("ma".into()),
            "MEX" => Some("mx".into()),
            "NED" => Some("nl".into()),
            "NOR" => Some("no".into()),
            "NZL" => Some("nz".into()),
            "QAT" => Some("qa".into()),
            "PAN" => Some("pa".into()),
            "PAR" => Some("py".into()),
            "POL" => Some("pl".into()),
            "POR" => Some("pt".into()),
            "ROU" => Some("ro".into()),
            "RSA" => Some("za".into()),
            "SCO" => Some("gb-sct".into()),
            "SEN" => Some("sn".into()),
            "SRB" => Some("rs".into()),
            "SUI" => Some("ch".into()),
            "SVK" => Some("sk".into()),
            "SVN" => Some("si".into()),
            "SWE" => Some("se".into()),
            "TUN" => Some("tn".into()),
            "TUR" => Some("tr".into()),
            "UKR" => Some("ua".into()),
            "URU" => Some("uy".into()),
            "USA" => Some("us".into()),
            "UZB" => Some("uz".into()),
            _ => None,
        }
    } else {
        None
    }
}
